# Generated by Django 4.2.29 on 2026-05-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
