# Generated by Django 4.2.29 on 2026-03-31 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_propiedad', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=50)),
                ('datos', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('videos_creados', models.IntegerField(default=0)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
