# Generated by Django 4.2.29 on 2026-03-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agentes_asociados',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='agent',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='nombre_inmobiliaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
