# Generated by Django 4.2.29 on 2026-04-01 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent_agentes_asociados_agent_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('properties_per_month', models.IntegerField(default=20)),
                ('ai_generations', models.IntegerField(default=50)),
                ('image_generations', models.IntegerField(default=20)),
                ('video_generations', models.IntegerField(default=0)),
                ('auto_posting', models.BooleanField(default=False)),
                ('voice_ai', models.BooleanField(default=False)),
                ('branding', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='plan_nombre',
            field=models.CharField(default='starter', max_length=20),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateTimeField(auto_now_add=True)),
                ('periodo_fin', models.DateTimeField(blank=True, null=True)),
                ('properties_used', models.IntegerField(default=0)),
                ('ai_used', models.IntegerField(default=0)),
                ('images_used', models.IntegerField(default=0)),
                ('videos_used', models.IntegerField(default=0)),
                ('extra_credits', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('agente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan')),
            ],
        ),
    ]
