# Generated by Django 4.2.29 on 2026-05-13 17:47

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comercialagentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_template_id', models.CharField(choices=[('dubai_night', 'Dubai Night'), ('beverly_hills', 'Beverly Hills'), ('manhattan', 'Manhattan'), ('mediterraneo', 'Mediterraneo'), ('tech_modern', 'Tech Modern')], default='tech_modern', max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandTemplateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField()),
                ('tokens_json', models.JSONField(default=api.models.default_template_tokens)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.RenameIndex(
            model_name='comercialagentprofile',
            new_name='api_comerci_owner_i_d38fb4_idx',
            old_name='api_comerci_owner_i_f4f2e2_idx',
        ),
        migrations.RenameIndex(
            model_name='comercialagentprofile',
            new_name='api_comerci_owner_i_39d410_idx',
            old_name='api_comerci_owner_i_4d2f98_idx',
        ),
        migrations.AddField(
            model_name='brandtemplaterevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_revisions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandtemplaterevision',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.brandtemplate'),
        ),
        migrations.AddField(
            model_name='brandtemplate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listado',
            name='brand_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listados', to='api.brandtemplate'),
        ),
        migrations.AddField(
            model_name='listado',
            name='brand_template_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listados', to='api.brandtemplaterevision'),
        ),
        migrations.AddIndex(
            model_name='brandtemplaterevision',
            index=models.Index(fields=['template', 'status'], name='api_brandte_templat_1b01ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='brandtemplaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'revision'), name='unique_template_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='brandtemplaterevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('template',), name='unique_published_revision_per_template'),
        ),
        migrations.AddIndex(
            model_name='brandtemplate',
            index=models.Index(fields=['owner', 'is_active'], name='api_brandte_owner_i_3b5e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='brandtemplate',
            index=models.Index(fields=['owner', 'is_default'], name='api_brandte_owner_i_ac8e3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='brandtemplate',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_brand_template_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='brandtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('owner',), name='unique_default_brand_template_per_owner'),
        ),
    ]
