# Generated by Django 4.2.29 on 2026-04-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plan_agent_plan_nombre_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_anual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_mensual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='stripe_status',
            field=models.CharField(default='free', max_length=30),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
