# Generated by Django 4.2.29 on 2026-04-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plan_stripe_price_id_anual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_anual',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_mensual',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='stripe_status',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='mp_plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='mp_status',
            field=models.CharField(default='free', max_length=30),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='mp_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
