# Generated by Django 4.2.29 on 2026-05-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_agentmediaasset_usercontentpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandtemplaterevision',
            name='gemini_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandtemplaterevision',
            name='preview_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
