# Generated by Django 4.2.29 on 2026-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_plan_stripe_price_id_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='nicho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
