# Generated by Django 4.2.29 on 2026-04-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agent_nicho_agent_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='listado',
            name='video_status',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='listado',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
