# Generated by Django 4.2.29 on 2026-05-16 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_property_usage_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFieldPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field', '-usage_count', '-last_used_at'],
                'indexes': [models.Index(fields=['user', 'field', '-usage_count'], name='api_userfie_user_id_9a3985_idx'), models.Index(fields=['user', 'last_used_at'], name='api_userfie_user_id_b4c1bd_idx')],
                'unique_together': {('user', 'field', 'value')},
            },
        ),
    ]
