# Generated by Django 4.2.29 on 2026-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_listado_video_status_listado_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='meta_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='meta_instagram_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
