# Generated by Django 4.2.29 on 2026-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrivacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Política de Privacidad', max_length=255)),
                ('contenido', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='TerminosCondiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Términos y Condiciones de Uso', max_length=255)),
                ('contenido', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
