# Generated by Django 4.2.29 on 2026-05-18 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_socialpublicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='free_trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='free_trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_days', models.PositiveSmallIntegerField(default=30)),
                ('assigned_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_codes', to=settings.AUTH_USER_MODEL)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_access_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'redeemed_at'], name='api_accessc_is_acti_01713e_idx'), models.Index(fields=['assigned_email'], name='api_accessc_assigne_a95232_idx')],
            },
        ),
    ]
