# Generated by Django 4.2.29 on 2026-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_politicaprivacidad_terminoscondiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mp_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='mp_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='plan_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='plan_seleccionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='plan_nombre',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('scale', 'Scale'), ('business', 'Business')], default='free', max_length=20),
        ),
    ]
