# Generated by Django 4.2.29 on 2026-04-08 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_agent_mp_customer_id_agent_mp_subscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenidadPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenidad_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('agente', 'nombre')},
            },
        ),
    ]
