# Generated by Django 4.2.29 on 2026-04-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_amenidadpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='mp_price_id_anual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='mp_price_id_mensual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
