# Generated by Django 4.2.29 on 2026-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_plan_billing_mensual_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='tipo',
            field=models.CharField(default='registro', max_length=20),
        ),
    ]
