# Generated by Django 4.2.29 on 2026-04-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_otpcode_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='plan',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
