# Generated by Django 4.2.29 on 2026-05-22 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_services_pool_and_media_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('meta', 'Meta'), ('web', 'Web'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual')], default='manual', max_length=24)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('won', 'Ganado'), ('lost', 'Perdido')], default='open', max_length=16)),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('contact_data', models.JSONField(blank=True, default=dict)),
                ('leadgen_id', models.CharField(blank=True, max_length=120, null=True)),
                ('form_id', models.CharField(blank=True, max_length=120, null=True)),
                ('page_id', models.CharField(blank=True, max_length=120, null=True)),
                ('campaign_id', models.CharField(blank=True, max_length=120, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adset_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ad_id', models.CharField(blank=True, max_length=120, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_leads', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to='api.listado')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(default='#00d4ff', max_length=24)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_pipeline_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Creado'), ('assigned', 'Asignado'), ('contacted', 'Contactado'), ('stage_changed', 'Cambio de etapa'), ('followup_created', 'Follow-up creado'), ('webhook_received', 'Webhook recibido'), ('note', 'Nota')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_lead_events', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_lead_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lead_assignment_authored', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lead_assignment_targets', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_lead_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='api.pipelinestage'),
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('done', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_up_tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_tasks', to='api.lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_follow_up_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['owner', 'is_active', 'order'], name='api_pipelin_owner_i_7470bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_crm_pipeline_stage_slug_per_owner'),
        ),
        migrations.AddIndex(
            model_name='leadevent',
            index=models.Index(fields=['lead', 'created_at'], name='api_leadeve_lead_id_338ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadevent',
            index=models.Index(fields=['owner', 'event_type', 'created_at'], name='api_leadeve_owner_i_df17ca_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['lead', 'is_active'], name='api_leadass_lead_id_ee4030_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['owner', 'assigned_to', 'is_active'], name='api_leadass_owner_i_d1d4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'origin', 'created_at'], name='api_lead_owner_i_c7d9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'pipeline_stage', 'updated_at'], name='api_lead_owner_i_3c5c70_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'sla_due_at'], name='api_lead_owner_i_6d59cf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['leadgen_id'], name='api_lead_leadgen_6f08ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('leadgen_id__isnull', False)), fields=('owner', 'origin', 'leadgen_id'), name='unique_crm_leadgen_per_owner_origin'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['owner', 'status', 'due_at'], name='api_followu_owner_i_e2320d_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['lead', 'status'], name='api_followu_lead_id_a03664_idx'),
        ),
    ]
