# Generated by Django 4.2.29 on 2026-04-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_agent_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='plan_activo',
            field=models.BooleanField(default=True),
        ),
    ]
