# Generated by Django 4.2.29 on 2026-04-13 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_agent_plan_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('gemini', 'Gemini'), ('elevenlabs', 'ElevenLabs'), ('uploadpost', 'Upload Post')], max_length=20)),
                ('api_key', models.TextField()),
                ('agotada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
