# Generated by Django 4.2.29 on 2026-04-13 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cuentapool'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ai', 'IA / Guion'), ('image', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'tipo', 'fecha'], name='api_usagelo_agent_i_42f793_idx')],
            },
        ),
    ]
