# Generated by Django 4.2.29 on 2026-04-28 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_usagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quota_warning', 'Quota Warning'), ('api_dead', 'API Dead'), ('user_abuse', 'User Abuse'), ('high_error_rate', 'High Error Rate')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('gemini', 'Gemini'), ('elevenlabs', 'ElevenLabs'), ('uploadpost', 'Upload Post')], max_length=20)),
                ('api_key', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('exhausted', 'Exhausted'), ('dead', 'Dead'), ('disabled', 'Disabled')], default='available', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('daily_limit', models.IntegerField(default=1500)),
                ('monthly_limit', models.IntegerField(blank=True, null=True)),
                ('requests_today', models.IntegerField(default=0)),
                ('requests_this_month', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.BooleanField(default=True)),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_key_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('characters_used', models.IntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('request_context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.apikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAPIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('daily_limit', models.IntegerField(default=1500)),
                ('monthly_limit', models.IntegerField(blank=True, null=True)),
                ('requests_today', models.IntegerField(default=0)),
                ('requests_this_month', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('last_reset_daily', models.DateTimeField(blank=True, null=True)),
                ('last_reset_monthly', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.CreateModel(
            name='UserBanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CuentaPool',
        ),
        migrations.AddField(
            model_name='adminalert',
            name='related_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apikey'),
        ),
        migrations.AddField(
            model_name='adminalert',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
