# Generated by Django 4.2.29 on 2026-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_adminalert_apikey_apirequestlog_userapiquota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
