# Generated by Django 4.2.29 on 2026-06-03 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cerebras_api_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryStorageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(blank=True, max_length=120)),
                ('asset_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('operation', models.CharField(choices=[('upload', 'Upload'), ('health_usage', 'Health usage'), ('health_probe', 'Health probe')], default='upload', max_length=30)),
                ('status', models.CharField(choices=[('success', 'Exitosa'), ('failed', 'Fallida'), ('skipped', 'Saltada')], db_index=True, default='failed', max_length=20)),
                ('public_id', models.CharField(blank=True, max_length=500)),
                ('resource_type', models.CharField(blank=True, max_length=30)),
                ('bytes', models.BigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('is_probe', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_apikey_servici_576501_idx',
            old_name='api_apikey_servici_1b4a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_apikey_slot_lo_6d103b_idx',
            old_name='api_apikey_slot_lo_93e50f_idx',
        ),
        migrations.AddField(
            model_name='cloudinarystoragelog',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloudinary_storage_logs', to='api.apikey'),
        ),
        migrations.AddField(
            model_name='cloudinarystoragelog',
            name='listado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloudinary_storage_logs', to='api.listado'),
        ),
        migrations.AddField(
            model_name='cloudinarystoragelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloudinary_storage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cloudinarystoragelog',
            index=models.Index(fields=['api_key', 'creado_en'], name='api_cloudin_api_key_82de03_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudinarystoragelog',
            index=models.Index(fields=['user', 'creado_en'], name='api_cloudin_user_id_3be3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudinarystoragelog',
            index=models.Index(fields=['listado', 'creado_en'], name='api_cloudin_listado_f11220_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudinarystoragelog',
            index=models.Index(fields=['asset_type', 'status'], name='api_cloudin_asset_t_b021df_idx'),
        ),
        migrations.AddIndex(
            model_name='cloudinarystoragelog',
            index=models.Index(fields=['operation', 'is_probe'], name='api_cloudin_operati_477439_idx'),
        ),
    ]
