# Generated by Django 4.2.29 on 2026-05-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_agent_eliminado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('assigned_to', 'servicio')},
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', False)), fields=('assigned_to', 'servicio'), name='unique_service_per_user'),
        ),
    ]
