# Generated by Django 4.2.29 on 2026-05-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_apikey_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='assets/music/')),
                ('duracion_segundos', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('swoosh', 'Swoosh'), ('impact', 'Impact'), ('camera', 'Camera'), ('other', 'Other')], default='other', max_length=20)),
                ('archivo', models.FileField(upload_to='assets/sfx/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
