# Generated by Django 4.2.29 on 2026-05-02 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_videomusic_videosfx'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Bundle #1 — Cuenta Google A', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Asignado'), ('retired', 'Retirado')], default='available', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Bundle',
                'verbose_name_plural': 'API Bundles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apikey',
            name='empresa',
            field=models.CharField(blank=True, help_text='Empresa/cuenta propietaria de la key', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='label',
            field=models.CharField(blank=True, help_text='Nombre descriptivo interno', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='servicio',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('elevenlabs', 'ElevenLabs'), ('uploadpost', 'Upload Post'), ('openai', 'OpenAI'), ('groq', 'Groq'), ('anthropic', 'Anthropic'), ('stability', 'Stability AI'), ('replicate', 'Replicate'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('in_bundle', 'En Bundle'), ('assigned', 'Asignada (legacy)'), ('exhausted', 'Agotada'), ('dead', 'Muerta'), ('disabled', 'Deshabilitada')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='APIBundleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('liberado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.apibundle')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_bundle_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Bundle',
                'verbose_name_plural': 'Asignaciones de Bundle',
            },
        ),
        migrations.AddField(
            model_name='apibundle',
            name='key_elevenlabs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_elevenlabs', to='api.apikey'),
        ),
        migrations.AddField(
            model_name='apibundle',
            name='key_gemini',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_gemini', to='api.apikey'),
        ),
        migrations.AddField(
            model_name='apibundle',
            name='key_uploadpost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_uploadpost', to='api.apikey'),
        ),
    ]
