# Generated by Django 4.2.29 on 2026-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_banned_email_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='servicio',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('elevenlabs', 'ElevenLabs'), ('uploadpost', 'Upload Post'), ('openai', 'OpenAI'), ('groq', 'Groq'), ('anthropic', 'Anthropic'), ('stability', 'Stability AI'), ('replicate', 'Replicate'), ('cloudinary', 'Cloudinary'), ('other', 'Otro')], max_length=20),
        ),
    ]
