# Generated by Django 4.2.29 on 2026-05-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_apikey_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
