# Generated by Django 4.2.29 on 2026-05-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_banned_ip_and_agent_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_monthly_exhausted',
            field=models.BooleanField(default=False, help_text='Indica si llegó al límite 100% de cuota mensual real'),
        ),
        migrations.AlterField(
            model_name='bannedemail',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
