# Generated by Django 4.2.29 on 2026-05-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_apikey_is_monthly_exhausted_alter_bannedemail_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='daily_limit',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userapiquota',
            name='daily_limit',
            field=models.IntegerField(default=20),
        ),
    ]
