# Generated by Django 4.2.29 on 2026-05-07 06:15

from django.db import migrations


def backfill_gemini_daily_limit(apps, schema_editor):
    """
    Actualiza todas las APIKey de Gemini que tenían daily_limit=1500 (el viejo default)
    al nuevo valor correcto de 20 (límite real del free tier de Gemini).
    También ajusta UserAPIQuota de gemini con el mismo valor.
    """
    APIKey = apps.get_model('api', 'APIKey')
    UserAPIQuota = apps.get_model('api', 'UserAPIQuota')

    # Actualizar APIKey de Gemini con el límite incorrecto
    updated_keys = APIKey.objects.filter(
        servicio='gemini',
        daily_limit=1500
    ).update(daily_limit=20)

    # Actualizar UserAPIQuota de gemini con el límite incorrecto
    updated_quotas = UserAPIQuota.objects.filter(
        service='gemini',
        daily_limit=1500
    ).update(daily_limit=20)

    print(f"[Migración] {updated_keys} APIKey de Gemini actualizadas a daily_limit=20")
    print(f"[Migración] {updated_quotas} UserAPIQuota de Gemini actualizadas a daily_limit=20")


def reverse_backfill(apps, schema_editor):
    """Reversión: devuelve el límite a 1500 (solo para poder revertir la migración si es necesario)."""
    APIKey = apps.get_model('api', 'APIKey')
    UserAPIQuota = apps.get_model('api', 'UserAPIQuota')
    APIKey.objects.filter(servicio='gemini', daily_limit=20).update(daily_limit=1500)
    UserAPIQuota.objects.filter(service='gemini', daily_limit=20).update(daily_limit=1500)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_update_daily_limit_default_to_20'),
    ]

    operations = [
        migrations.RunPython(backfill_gemini_daily_limit, reverse_backfill),
    ]
