# Generated by Django 4.2.29 on 2026-05-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleAPIExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(default='gemini', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('comprada_en', models.DateTimeField(auto_now_add=True)),
                ('pago_id', models.CharField(blank=True, max_length=200, null=True)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras', to='api.apikey')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis_extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-comprada_en'],
            },
        ),
    ]
