"""
Django settings for subzero_core project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Aumentar hilos para vistas síncronas largas (como Gemini)
os.environ.setdefault("ASGI_THREADS", "100")
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS_ENV = config('ALLOWED_HOSTS', default='')
_env_allowed_hosts = [h.strip() for h in ALLOWED_HOSTS_ENV.split(',') if h.strip()]
_default_allowed_hosts = [
    '.up.railway.app',
    'backend-production-cd305.up.railway.app',
    'leadbook.com.ar',
    'www.leadbook.com.ar',
    'localhost',
    '127.0.0.1',
]
if '*' in _env_allowed_hosts and DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = list(dict.fromkeys([h for h in _env_allowed_hosts if h != '*'] + _default_allowed_hosts))

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    
    # Third party
    'cloudinary',
    'rest_framework',
    'corsheaders',

    # Local
    'api',
    'admin_panel',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
]

AUTH_USER_MODEL = 'api.Agent'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'subzero_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'subzero_core.wsgi.application'
ASGI_APPLICATION = 'subzero_core.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_DATABASE_URL = config("DATABASE_URL", default="").strip()

if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=_DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG
        )
    }
else:
    # Ruta del SQLite: permite override por SQLITE_PATH (útil en filesystems
    # donde BASE_DIR no soporta locking, p.ej. algunos mounts virtuales).
    _sqlite_path = config('SQLITE_PATH', default=str(BASE_DIR / 'db.sqlite3'))
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _sqlite_path,
            'OPTIONS': {'timeout': 20},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('DRF_THROTTLE_ANON', default='120/minute'),
        'user': config('DRF_THROTTLE_USER', default='600/minute'),
    },
}

from datetime import timedelta
from celery.schedules import crontab
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS Configuration
CORS_ALLOWED_ORIGINS_ENV = config('CORS_ALLOWED_ORIGINS', default='')
_env_origins = [o.strip() for o in CORS_ALLOWED_ORIGINS_ENV.split(',') if o.strip()]
_production_origins = [
    'https://dash-admin-leadbook.vercel.app',
    'https://leadbook.com.ar',
    'https://www.leadbook.com.ar',
]
_local_origins = [
    'http://localhost:5173',
    'http://localhost:4173',
    'http://localhost:3000',
]
CORS_ALLOWED_ORIGINS = list(dict.fromkeys(_env_origins + _production_origins + (_local_origins if DEBUG else [])))
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://leadbook\.com\.ar$',
    r'^https://www\.leadbook\.com\.ar$',
    r'^https://[a-z0-9-]+\.vercel\.app$',
    r'^https://[a-z0-9-]+\.up\.railway\.app$',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type', 'dnt',
    'origin', 'user-agent', 'x-csrftoken', 'x-requested-with', 'x-admin-key',
]
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
print(f"[STARTUP] CORS_ALLOWED_ORIGINS={CORS_ALLOWED_ORIGINS}")

CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(
    [o.strip() for o in config('CSRF_TRUSTED_ORIGINS', default='https://dash-admin-leadbook.vercel.app').split(',') if o.strip()]
    + _production_origins
))

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=(31536000 if not DEBUG else 0), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=not DEBUG, cast=bool)
X_FRAME_OPTIONS = 'DENY'

REMOTE_ASSET_ALLOWED_HOSTS = [
    host.strip().lower()
    for host in config('REMOTE_ASSET_ALLOWED_HOSTS', default='res.cloudinary.com,placehold.co').split(',')
    if host.strip()
]

# Celery Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://127.0.0.1:6379/0')
# En local sin Redis puede activarse con CELERY_TASK_ALWAYS_EAGER=True.
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=DEBUG, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BEAT_SCHEDULE = {
    'reset-free-pool-counters-every-12-hours': {
        'task': 'api.tasks.reset_free_pool_counters',
        'schedule': timedelta(hours=12),
    },
    'reset-daily-counters-midnight': {
        'task': 'api.tasks.reset_daily_counters',
        'schedule': crontab(hour=0, minute=0),
    },
}

# Cache Configuration — usa Redis si está disponible, sino memoria local
_REDIS_URL = config('REDIS_URL', default='')
if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _REDIS_URL,
        }
    }
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [_REDIS_URL],
            },
        },
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "leadbook-cache",
        }
    }
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

# Cloudinary Configuration
import cloudinary

cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME', default=''),
    api_key=config('CLOUDINARY_API_KEY', default=''),
    api_secret=config('CLOUDINARY_API_SECRET', default='')
)

VIDEO_ENGINE_DIR = os.path.join(BASE_DIR, 'hyperframes_engine')

# External APIs
GEMINI_API_KEY     = config('GEMINI_API_KEY', default='')
GROQ_API_KEY       = config('GROQ_API_KEY', default='')
ELEVENLABS_API_KEY = config('ELEVENLABS_API_KEY', default='')
UPLOADPOST_API_KEY = config('UPLOADPOST_API_KEY', default='')
NVIDIA_API_KEY     = config('NVIDIA_API_KEY', default='')

# Twilio / WhatsApp
TWILIO_ACCOUNT_SID  = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN   = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = config('TWILIO_WHATSAPP_FROM', default='whatsapp:+14155238886')
WHATSAPP_ENABLED     = config('WHATSAPP_ENABLED', default=False, cast=bool)

# MercadoPago Configuration
MP_MODE           = config('MP_MODE', default='production').strip().lower()
MP_ACCESS_TOKEN   = config('MP_ACCESS_TOKEN', default='')
MP_PUBLIC_KEY     = config('MP_PUBLIC_KEY', default='')
MP_WEBHOOK_SECRET = config('MP_WEBHOOK_SECRET', default='')
BACKEND_URL       = config('BACKEND_URL', default='http://localhost:8000')
FRONTEND_URL      = config('FRONTEND_URL', default='http://localhost:5173')

# Email / SMTP Configuration
# Si no hay GMAIL_APP_PASSWORD se usa el console backend (OTP impreso por stdout).
EMAIL_PROVIDER      = config('EMAIL_PROVIDER', default='').strip().lower()
RESEND_API_KEY     = config('RESEND_API_KEY', default='')
RESEND_FROM        = config('RESEND_FROM', default='')
EMAIL_HOST_USER     = config('GMAIL_USER', default='')
EMAIL_HOST_PASSWORD = config('GMAIL_APP_PASSWORD', default='')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST    = 'smtp.gmail.com'
    EMAIL_PORT    = 465
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = True
    DEFAULT_FROM_EMAIL = f'LeadBook <{EMAIL_HOST_USER}>'
    print(f"[STARTUP] EMAIL_BACKEND=SMTP | host={EMAIL_HOST}:{EMAIL_PORT}")
else:
    # Fallback de desarrollo: imprime los emails en la consola
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST    = 'smtp.gmail.com'
    EMAIL_PORT    = 465
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = True
    DEFAULT_FROM_EMAIL = 'LeadBook <no-reply@leadbook.local>'
    print("[STARTUP] EMAIL_BACKEND=CONSOLE (falta GMAIL_USER o GMAIL_APP_PASSWORD en env) "
          f"GMAIL_USER_set={bool(EMAIL_HOST_USER)} GMAIL_APP_PASSWORD_set={bool(EMAIL_HOST_PASSWORD)}")

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default='')
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

X_FRAME_OPTIONS = 'DENY'
