from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from . import views_usage
from .views import (
    PropertyViewSet, GeneratedAssetViewSet, generar_guion, generar_listado, 
    RegisterView, LogoutView, DashboardView, ListadosView, generar_pdf, 
    PerfilView, ListadoDetalleView, generar_imagen_post, generar_imagen_story, 
    generar_email, generar_caption_story, serve_pdf_file, mp_checkout, mp_webhook, get_plan_info_mp,
    OnboardingView, video_status, publicar_instagram, send_otp, verify_otp, request_trial_token, validate_access_code,
    generar_video, obtener_terminos, obtener_politica_privacidad,
    plan_status, seleccionar_plan_free, test_upload_avatar, generar_carrusel,
    amenidades_presets, field_presets_collection, field_preset_detail,
    recuperar_password, confirmar_recuperacion,
    publicar_redes_sociales, publicar_redes_todo, publicar_redes_status, publicar_redes_logs,
    proxy_pdf_view, proxy_pdf_thumbnail_view,
    generar_html, generar_escena, CustomTokenObtainPairView,
    upload_fotos_listado, templates_catalog,
    export_listado_zip, commercial_agents_collection,
    commercial_agent_detail, commercial_agent_set_default,
    commercial_agent_photo, content_preferences_detail,
    crm_clients_collection, crm_client_detail,
    extract_listado_from_url, generate_meta_variants,
    brand_templates_collection, brand_template_detail,
    brand_template_clone, brand_templates_options,
    brand_template_set_default, brand_template_revisions_collection,
    brand_template_publish_revision, brand_template_preview, brand_template_chat,
    brand_template_draft_preview, brand_template_draft_chat, CookieTokenRefreshView,
    cambiar_password, password_change_code, logout_all,
    start_content_generation_pack, content_generation_run_detail, retry_content_generation_run,
    advance_content_generation_run, video_studio_quick_base,
)
from .views_admin import (
    admin_metricas, admin_usuarios_list, admin_usuario_cambiar_plan, admin_usuario_eliminar,
    admin_usuario_detalle, admin_usuarios_eliminados, admin_usuario_restaurar,
    admin_usuario_suspender, admin_apikeys_resumen, admin_apikeys_pool,
    admin_apikeys_pool_crear, admin_apikeys_pool_bulk, admin_apikeys_pool_detail, admin_apikeys_global,
    admin_cerebras_usage_logs, admin_api_usage_summary, admin_api_usage_logs, admin_api_usage_key_detail,
    admin_ai_root, admin_ai_root_test,
    admin_pool_estado, admin_alerts_read, admin_health_check, admin_enviar_email,
    admin_bundles_list, admin_bundles_crear, admin_bundles_detail, admin_add_extra_api,
    admin_bundles_asignar, admin_bundles_liberar, admin_bundles_stats,
    admin_audio_music, admin_audio_music_detail, admin_audio_sfx, admin_audio_sfx_detail,
    admin_apikeys_auto_repair, admin_branding_watermark,
    admin_access_codes, admin_access_code_detail,
)
from .admin import admin_alerts_list
from .views_crm import (
    crm_client_send_email,
    crm_followup_task_detail,
    crm_lead_detail,
    crm_lead_mark_contacted,
    crm_lead_move_stage,
    crm_leads_collection,
    crm_metrics_view,
    crm_pipeline_stages,
    meta_leads_webhook,
)
from admin_panel.auth import admin_session_login, admin_session_profile

router = DefaultRouter()
router.register(r'properties', PropertyViewSet)
router.register(r'assets', GeneratedAssetViewSet)

urlpatterns = [
    path('auth/register/', RegisterView.as_view(), name='auth_register'),
    path('auth/login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/admin-login/', admin_session_login, name='admin_session_login'),
    path('auth/admin-profile/', admin_session_profile, name='admin_session_profile'),
    path('auth/login/refresh/', CookieTokenRefreshView.as_view(), name='token_refresh'),
    path('auth/token/refresh/', CookieTokenRefreshView.as_view(), name='token_refresh_alt'),
    path('auth/logout/', LogoutView.as_view(), name='auth_logout'),
    path('auth/logout-all/', logout_all, name='auth_logout_all'),
    path('auth/cambiar-password/', cambiar_password, name='auth_cambiar_password'),
    path('auth/password-change-code/', password_change_code, name='auth_password_change_code'),
    path('auth/perfil/', PerfilView.as_view(), name='auth_perfil'),
    path('auth/onboarding/', OnboardingView.as_view(), name='auth_onboarding'),
    path('auth/agentes-comerciales/', commercial_agents_collection, name='commercial_agents_collection'),
    path('auth/agentes-comerciales/<int:agent_id>/', commercial_agent_detail, name='commercial_agent_detail'),
    path('auth/agentes-comerciales/<int:agent_id>/set-default/', commercial_agent_set_default, name='commercial_agent_set_default'),
    path('auth/agentes-comerciales/<int:agent_id>/foto/', commercial_agent_photo, name='commercial_agent_photo'),
    path('auth/content-preferences/', content_preferences_detail, name='content_preferences_detail'),
    path('auth/crm/clientes/', crm_clients_collection, name='crm_clients_collection'),
    path('auth/crm/clientes/<int:client_id>/', crm_client_detail, name='crm_client_detail'),
    path('auth/crm/clientes/<int:client_id>/email/', crm_client_send_email, name='crm_client_send_email'),
    path('auth/crm/pipeline/', crm_pipeline_stages, name='crm_pipeline_stages'),
    path('auth/crm/leads/', crm_leads_collection, name='crm_leads_collection'),
    path('auth/crm/leads/<int:lead_id>/', crm_lead_detail, name='crm_lead_detail'),
    path('auth/crm/leads/<int:lead_id>/move/', crm_lead_move_stage, name='crm_lead_move_stage'),
    path('auth/crm/leads/<int:lead_id>/contacted/', crm_lead_mark_contacted, name='crm_lead_mark_contacted'),
    path('auth/crm/tasks/<int:task_id>/', crm_followup_task_detail, name='crm_followup_task_detail'),
    path('auth/crm/metrics/', crm_metrics_view, name='crm_metrics'),
    path('auth/templates/', brand_templates_collection, name='brand_templates_collection'),
    path('auth/templates/options/', brand_templates_options, name='brand_templates_options'),
    path('auth/templates/clone/', brand_template_clone, name='brand_template_clone'),
    path('auth/templates/draft-preview/', brand_template_draft_preview, name='brand_template_draft_preview'),
    path('auth/templates/draft-chat/', brand_template_draft_chat, name='brand_template_draft_chat'),
    path('auth/templates/<int:template_id>/', brand_template_detail, name='brand_template_detail'),
    path('auth/templates/<int:template_id>/set-default/', brand_template_set_default, name='brand_template_set_default'),
    path('auth/templates/<int:template_id>/preview/', brand_template_preview, name='brand_template_preview'),
    path('auth/templates/<int:template_id>/chat/', brand_template_chat, name='brand_template_chat'),
    path('auth/templates/<int:template_id>/revisions/', brand_template_revisions_collection, name='brand_template_revisions_collection'),
    path('auth/templates/<int:template_id>/publish/<int:revision_id>/', brand_template_publish_revision, name='brand_template_publish_revision'),
    path('auth/send-otp/', send_otp, name='auth_send_otp'),
    path('auth/verify-otp/', verify_otp, name='auth_verify_otp'),
    path('auth/request-trial-token/', request_trial_token, name='auth_request_trial_token'),
    path('auth/validate-access-code/', validate_access_code, name='auth_validate_access_code'),
    path('auth/plan-status/', plan_status, name='plan_status'),
    path('auth/seleccionar-plan-free/', seleccionar_plan_free, name='seleccionar_plan_free'),
    path('auth/recuperar-password/', recuperar_password, name='auth_recuperar_password'),
    path('auth/confirmar-recuperacion/', confirmar_recuperacion, name='auth_confirmar_recuperacion'),
    path('recuperar-password/', recuperar_password, name='recuperar_password'),
    path('confirmar-recuperacion/', confirmar_recuperacion, name='confirmar_recuperacion'),
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('listados/', ListadosView.as_view(), name='listados'),
    path('listados/<int:pk>/', ListadoDetalleView.as_view(), name='listado_detalle'),
    path('listados/extract-from-url/', extract_listado_from_url, name='extract_listado_from_url'),
    path('listados/upload-fotos/', upload_fotos_listado, name='upload_fotos_listado'),
    path('listados/<int:pk>/html/', generar_html, name='generar_html'),
    path('listados/<int:pk>/export-zip/', export_listado_zip, name='export_listado_zip'),
    path('listados/<int:pk>/generar-pack/', start_content_generation_pack, name='start_content_generation_pack'),
    path('generation-runs/<int:run_id>/', content_generation_run_detail, name='content_generation_run_detail'),
    path('generation-runs/<int:run_id>/advance/', advance_content_generation_run, name='advance_content_generation_run'),
    path('generation-runs/<int:run_id>/retry/', retry_content_generation_run, name='retry_content_generation_run'),
    path('listados/<int:pk>/generar-video/', generar_video, name='generar_video'),
    path('listados/<int:pk>/video/', generar_video, name='generar_video_legacy'),
    path('listados/<int:listado_id>/video-status/', video_status, name='video_status_legacy'),
    path('video-studio/quick-base/', video_studio_quick_base, name='video_studio_quick_base'),
    path('listados/<int:listado_id>/pdf-proxy/', proxy_pdf_view, name='pdf_proxy'),
    path('listados/<int:listado_id>/pdf-thumbnail/', proxy_pdf_thumbnail_view, name='pdf_thumbnail'),
    path('descargar-pdf/<int:listado_id>/', views.descargar_pdf, name='descargar_pdf'),

    path('', include(router.urls)),
    path('generar-guion/', generar_guion, name='generar_guion'),
    path('generar-escena/', generar_escena, name='generar_escena'),
    path('generar-listado/', generar_listado, name='generar_listado'),
    path('generar-pdf/', generar_pdf, name='generar_pdf'),
    path('generar-imagen-post/', generar_imagen_post, name='generar_imagen_post'),
    path('generar-imagen-story/', generar_imagen_story, name='generar_imagen_story'),
    path('generar-caption-story/', generar_caption_story, name='generar_caption_story'),
    path('generar-email/', generar_email, name='generar_email'),
    path('ads/generate-meta-variants/', generate_meta_variants, name='generate_meta_variants'),
    path('templates-catalog/', templates_catalog, name='templates_catalog'),
    path('publicar-instagram/', publicar_instagram, name='publicar_instagram'),
    path('publicar-redes/', publicar_redes_sociales, name='publicar_redes_sociales'),
    path('publicar-redes/todo/', publicar_redes_todo, name='publicar_redes_todo'),
    path('publicar-redes/status/', publicar_redes_status, name='publicar_redes_status'),
    path('publicar-redes/logs/', publicar_redes_logs, name='publicar_redes_logs'),
    path('pdf/<str:uuid_str>/', serve_pdf_file, name='serve_pdf'),
    path('video-status/<int:listado_id>/', video_status, name='video_status'),
    
    path('mp/checkout/', mp_checkout,  name='mp_checkout'),
    path('mp/webhook/',  mp_webhook,   name='mp_webhook'),
    path('mp/plan/',     get_plan_info_mp,       name='mp_plan_info'),
    path('crm/meta/webhook/', meta_leads_webhook, name='crm_meta_leads_webhook'),

    # Legal
    path('terminos-y-condiciones/', obtener_terminos, name='obtener_terminos'),
    path('politica-privacidad/', obtener_politica_privacidad, name='obtener_politica_privacidad'),

    # Test endpoints
    path('test-upload/', test_upload_avatar, name='test_upload_avatar'),
    path('generar-carrusel/', generar_carrusel, name='generar_carrusel'),
    path('amenidades-presets/', amenidades_presets, name='amenidades_presets'),
    path('field-presets/', field_presets_collection, name='field_presets_collection'),
    path('field-presets/<int:preset_id>/', field_preset_detail, name='field_preset_detail'),

    # Admin Dash
    path('admin/stats/', admin_metricas),
    path('admin/usuarios/', admin_usuarios_list),
    path('admin/usuarios-eliminados/', admin_usuarios_eliminados),
    path('admin/usuarios/<int:user_id>/', admin_usuario_eliminar),
    path('admin/usuarios/<int:user_id>/restaurar/', admin_usuario_restaurar),
    path('admin/usuarios/<int:user_id>/detalle/', admin_usuario_detalle),
    path('admin/usuarios/<int:user_id>/cambiar-plan/', admin_usuario_cambiar_plan),
    path('admin/usuarios/<int:user_id>/suspender/', admin_usuario_suspender),
    path('admin/usuarios/<int:user_id>/email/', admin_enviar_email),
    path('admin/users/<int:user_id>/add-extra/', admin_add_extra_api),
    path('admin/listados/', views.admin_listados),
    path('admin/assets/', views.admin_assets),
    path('admin/pagos/', views.admin_pagos),
    
    # API Keys & Pool
    path('admin/apikeys/resumen/', admin_apikeys_resumen),
    path('admin/apikeys/pool/', admin_apikeys_pool),
    path('admin/apikeys/pool/crear/', admin_apikeys_pool_crear),
    path('admin/apikeys/pool/bulk/', admin_apikeys_pool_bulk),
    path('admin/apikeys/pool/<int:key_id>/', admin_apikeys_pool_detail),
    path('admin/apikeys/pool/<int:key_id>/detalle/', admin_apikeys_pool_detail),
    path('admin/apikeys/global/', admin_apikeys_global),
    path('admin/cerebras/logs/', admin_cerebras_usage_logs),
    path('admin/api-usage/summary/', admin_api_usage_summary),
    path('admin/api-usage/logs/', admin_api_usage_logs),
    path('admin/api-usage/keys/<int:key_id>/', admin_api_usage_key_detail),
    path('admin/ai-root/', admin_ai_root),
    path('admin/ai-root/test/', admin_ai_root_test),
    path('admin/apikeys/pool/auto-repair/', admin_apikeys_auto_repair),
    path('admin/pool/estado/', admin_pool_estado),
    path('admin/pool/listar/', admin_apikeys_pool), # Alias
    path('admin/alerts/', admin_alerts_list),
    path('admin/alerts/<int:alert_id>/read/', admin_alerts_read),
    path('admin/health-check/', admin_health_check),
    path('admin/access-codes/', admin_access_codes),
    path('admin/access-codes/<int:code_id>/', admin_access_code_detail),

    # Conexiones Redes (UploadPost)
    path('conexiones/init/', views.conexiones_init),
    path('conexiones/estado/', views.conexiones_estado),
    path('conexiones/eliminar/', views.conexiones_eliminar),

    # Debug / Diagnóstico
    path('debug/email-check/', views.debug_email_check, name='debug_email_check'),
    path('debug/email-send/',  views.debug_email_send,  name='debug_email_send'),
    path('debug/uploadpost/<str:username>/', views.debug_uploadpost, name='debug_uploadpost'),

    # Uso de APIs
    path('auth/mi-uso/', views_usage.mi_uso_apis, name='mi_uso_apis'),
    path('admin/uso-global/', views_usage.admin_uso_global, name='admin_uso_global'),

    # API Bundles
    path('admin/bundles/', admin_bundles_list),
    path('admin/bundles/crear/', admin_bundles_crear),
    path('admin/bundles/stats/', admin_bundles_stats),
    path('admin/bundles/<int:bundle_id>/', admin_bundles_detail),
    path('admin/bundles/<int:bundle_id>/asignar/', admin_bundles_asignar),
    path('admin/bundles/<int:bundle_id>/liberar/', admin_bundles_liberar),

    # Librería de Audio
    path('admin/audio/music/', admin_audio_music),
    path('admin/audio/music/<int:pk>/', admin_audio_music_detail),
    path('admin/audio/sfx/', admin_audio_sfx),
    path('admin/audio/sfx/<int:pk>/', admin_audio_sfx_detail),
    path('admin/branding/watermark/', admin_branding_watermark),

    # Notificaciones
    path('notificaciones/', views.listar_notificaciones),
    path('notificaciones/<int:notif_id>/leer/', views.marcar_notificacion_leida),
    path('notificaciones/leer-todas/', views.marcar_todas_leidas),
    path('cuota-ia/', views.estado_cuota_ia),
    path('mp/checkout-extra/', views.mp_checkout_api_extra),
    path('debug/quota/', views.debug_quota),
]
